# Generated by Django 5.2.4 on 2025-09-06 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_article_options_article_meta_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='article',
            name='meta_title',
        ),
    ]
