# Generated by Django 5.2.4 on 2025-09-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_remove_article_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique_for_date='name'),
        ),
    ]
