# Generated by Django 5.2.4 on 2025-09-13 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_article_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedarticle',
            options={'ordering': ['-saved_at'], 'verbose_name': 'مقال محفوظ', 'verbose_name_plural': 'المقالات المحفوظة'},
        ),
        migrations.RenameField(
            model_name='savedarticle',
            old_name='created_at',
            new_name='saved_at',
        ),
    ]
