# Generated by Django 5.2.4 on 2025-09-13 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_savedarticle_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
