# Generated by Django 5.2.4 on 2025-09-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_remove_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='descreption',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
