# Generated by Django 5.2.4 on 2025-09-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_category_descreption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='descreption',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique=True),
        ),
    ]
