# Generated by Django 5.2.4 on 2025-09-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_alter_category_options_remove_category_descreption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='featured',
            field=models.BooleanField(blank=True, default=False, verbose_name='مميز'),
        ),
    ]
